name: Merge to dev

on:
  push:
    branches:
    - "master"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "dev"
        pr_title: "Pulling master into dev"               # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_reviewer: "steven-murray"                      # Comma-separated list (no spaces)
        pr_assignee: "steven-murray"                      # Comma-separated list (no spaces)
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        github_token: ${{ secrets.BUMP_VERSION }}

  merge-me:
    name: Merge me!
    needs:
      - pull-request
    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v1
        with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` environment variable with permissions to
          # push to a protected branch must be used. This variable can have an
          # arbitrary name, as an example, this repository uses
          # `GITHUB_TOKEN_DOTTBOTT`.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support
          # pushing to protected branches.
          GITHUB_TOKEN: ${{ secrets.BUMP_VERSION }}
